#! python3
# BulletPointAdder.py - добавляет звёздочку в начале каждой строки

import pyperclip

text = pyperclip.paste()

# Задача: сделать функцию
lines = text.split('\n')
for i in range(len(lines)):
    lines[i] = '*' + lines[i]

text = '\n'.join(lines)
pyperclip.copy(text)
print(text)
